const moreGoods = [
    {
        id: 1,
        link: "https://www.crotonmotors.com/wp-content/uploads/2019/01/2013-Mercedes-Benz-ML350-BlueTEC-4MATIC.jpg",
        srcSet: [
            "https://th.bing.com/th/id/R.7e419004cd4b4a990ed7c3a76f91bea7?rik=uLXJ93RGOPTwLg&riu=http%3a%2f%2ftopcarspecs.com%2fmanufacturers%2fmercedes-benz%2fmercedes-benz-suv%2fmercedes-benz-suv-2014%2fmercedes-benz-suv-2014-3.jpg&ehk=L8Fy8a%2bk4CsBT330Op8cBe5IACec%2fpy6NP1BpNuFSfY%3d&risl=&pid=ImgRaw&r=0",
            "https://th.bing.com/th/id/R.dded6be660232790d848f5b7ee8cae3d?rik=1zLH5yrel30fHA&riu=http%3a%2f%2fwww.whichcarisrightforme.com%2fcdn%2fimages%2fmanufacturer%2fMercedes-Benz%2fML-Class%2f2012%2fgallery_1.jpg&ehk=4n%2bq5HOEV5iD9QC93RzRTGOmjy3sMhqBE%2bG2K5UI2IY%3d&risl=&pid=ImgRaw&r=0",
            "https://th.bing.com/th/id/OIP.svyC-aAV-e09H-LWoFaQCgHaFj?pid=ImgDet&w=2048&h=1536&rs=1",
        ],
        price: "KSh 3,200,000",
        name: "Mercedes Benz C200 2015",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        features: [
            "Combine luxury with reliability",
            "Spacious interior for up to five passengers",
            "Efficient engine and fuel efficiency of up to 20 km per liter",
        ],
    },
    {
        id: 2,
        link: "https://shop.texasmediasystems.com/assets/images/products/sony/xdcam/sony_pxw-x200_a_web.jpg",
        srcSet: [
            "https://pro.sony/s3/2018/04/04151850/fs5-update_discover-fs5-2.png",
            "https://th.bing.com/th/id/OIP.Kxi2sp37zKIzLW_Ss6UDfgHaFF?pid=ImgDet&w=1600&h=1100&rs=1",
            "https://i.pinimg.com/474x/11/53/6a/11536a58bbf6af9178e5c85144ae31ae--antique-cameras-camcorder.jpg",
        ],
        price: "KSh 120,000",
        name: "PXW-Z100, Ushers Era of 4K Camcorder",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        features: [
            "Ultrazoom lens",
            "Capture stunning images in 4k resolution",
            "Up to 1 hour continuous shooting",
        ],
    },
    {
        id: 3,
        link: "https://th.bing.com/th/id/R.7c2f79d9ed31138d26c588bb554fbb64?rik=5H%2f9HwpSZUGApA&riu=http%3a%2f%2fwww.tarheelfoodie.com%2fwp-content%2fuploads%2f2011%2f02%2fDSC03733.jpg&ehk=HYqHCUTbyb%2fKYD2aS4PzqM5dMoNfs7BYhw7vytysuTA%3d&risl=&pid=ImgRaw&r=0",
        srcSet: [
            "https://th.bing.com/th/id/R.1263e5c67599ba6b27741258e37f0862?rik=czbhfLNqdZMSyQ&riu=http%3a%2f%2fwww.andiemitchell.com%2fwp-content%2fuploads%2f2011%2f07%2ffavorite-foods-018.jpg&ehk=AvmDNMQrCtf2yUsfW%2b1nPHhWwAcEQ1GylEQiMtBiHSI%3d&risl=&pid=ImgRaw&r=0",
            "https://th.bing.com/th/id/R.d95d02c96fa7ddf8f66afb82019dbb32?rik=TbEgj6DLscJsVg&pid=ImgRaw&r=0",
            "https://th.bing.com/th/id/OIP.JYtDgY3Gn-gk5dyeAMMregAAAA?pid=ImgDet&w=474&h=315&rs=1",
        ],
        price: "KSh 330",
        name: "Eggs @ Tray",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        features: [
            "Fresh eggs from the farm",
            "Perfectly packed, refrigerated and on trays",
            "Free delivery within Nairobi & Kericho town area",
        ],
    },
    {
        id: 4,
        link: "https://th.bing.com/th/id/OIP.NLS4qJ04U17h82zYZarTNgHaE_?pid=ImgDet&rs=1",
        srcSet: [
            "https://th.bing.com/th/id/OIP.yzFjnrdvGnDdUtEQ4f34bAHaHa?pid=ImgDet&w=1800&h=1800&rs=1",
            "https://th.bing.com/th/id/OIP.JNwsmmDlhTT5qJzgg5fdFgHaHa?pid=ImgDet&w=1000&h=1000&rs=1",
            "https://th.bing.com/th/id/OIP.uaZVep_f_S9QjVuIhaEvjgHaHa?pid=ImgDet&w=1000&h=1000&rs=1",
        ],
        price: "KSh 2,700",
        name: "Essential Hoodies",
        category: "Fashion",
        location: "Thika, Kiambu",
        mobile: "+254717405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        features: [
            "Large sizes available for men, women or children",
            "Soft and breathable materials",
            "Comfortable hoodie with a relaxing feel",
            "Washable in cold water",
        ],
    },
    {
        id: 5,
        link: "https://th.bing.com/th/id/OIP.RYm9p2U3vJtNtT2pkmozmgHaFj?pid=ImgDet&rs=1",
        srcSet: [
            "https://th.bing.com/th/id/OIP.69hlwHEb9TyCFCTUVSh19gHaFj?pid=ImgDet&w=474&h=355&rs=1",
            "https://th.bing.com/th/id/OIP.vkWCAE_pKfug_i23te13AwHaFj?pid=ImgDet&w=474&h=355&rs=1",
            "https://th.bing.com/th/id/OIP.49OPMwWonAIsC4b6S_1AHgHaFj?pid=ImgDet&w=474&h=355&rs=1",
        ],
        price: "KSh 4,650,000",
        name: "Toyota Fortuner 2016",
        category: "Vehicles",
        location: "Starehe, Nairobi",
        mobile: "+254717405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        features: [
            "Automatic Transmission",
            "Leather Seats",
            "Power Steering",
            "Alloy Wheels",
            "CD Player",
            "AM/FM Radio",
            "Power Windows",
            "Power Door Locks",
            "Front Air Conditioning",
            "Rear Window Wiper",
            "Steel Brakes",
            "Power Sunroof",
            "Antilock Brake System (ABS)",
            "Central Locking",
            "Keyless Entry",
        ],
    },
    // {
    //     link: "https://images.pexels.com/photos/2403391/pexels-photo-2403391.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Get to your nearest restaurant",
    //     category: "Services",
    //     location: "Upperhill, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2912108/pexels-photo-2912108.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Wines (Delivery)",
    //     category: "Drinks",
    //     location: "Westlands, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/952264/pexels-photo-952264.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 72,000",
    //     name: "Nikon D7500",
    //     category: "Cameras",
    //     location: "CBD, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5709648/pexels-photo-5709648.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 3,200",
    //     name: "Hawaiian Hat for Women",
    //     category: "Fashion",
    //     location: "CBD, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/6126310/pexels-photo-6126310.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Outdoor Dining Palace",
    //     category: "Food",
    //     location: "Westlands, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2995012/pexels-photo-2995012.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 72,000",
    //     name: "Dining Table",
    //     category: "Interior",
    //     location: "Makadara, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5230908/pexels-photo-5230908.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 12,000",
    //     name: "Agricultural carts",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 17,500",
    //     name: "Women's handbags",
    //     category: "Fashion",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5709655/pexels-photo-5709655.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 24,400",
    //     name: "Assorted Fabric Bags",
    //     category: "Fashion",
    //     location: "Eastleigh, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2129654/pexels-photo-2129654.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 1,000",
    //     name: "Adult Chicken",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/6294166/pexels-photo-6294166.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 350",
    //     name: "Eggs @ Tray",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5945657/pexels-photo-5945657.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 1,350",
    //     name: "Tomatoes @ 90 KG",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5699068/pexels-photo-5699068.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 8,550",
    //     name: "Cowboy Hats",
    //     category: "Fashion",
    //     location: "CBD, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7832983/pexels-photo-7832983.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Order Fast Food + Delivery",
    //     category: "Services",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/11568799/pexels-photo-11568799.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Contact your nearest fast food restaurant",
    //     category: "Services",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/6280388/pexels-photo-6280388.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 450",
    //     name: "Spinach @ 15KG",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://media.istockphoto.com/id/1158134822/photo/kfc-style-fried-chicken-nuggets-takeaway-in-black-container.jpg?b=1&s=612x612&w=0&k=20&c=86DcrfP_oV4GO5BXeYanj5dj0t64EqOld1fMC_6f34U=",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Order Fast Food + Delivery",
    //     category: "Services",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1841120/pexels-photo-1841120.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 7,000,000",
    //     name: "Cadillac 1979 Etzy Model",
    //     category: "Vehicles",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/794435/pexels-photo-794435.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 4,300,000",
    //     name: "BMW M3 2015 M Competition Edition",
    //     category: "Vehicles",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5905486/pexels-photo-5905486.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "",
    //     name: "Hire a Tutor",
    //     category: "Services",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2023384/pexels-photo-2023384.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 48,000",
    //     name: "Rottweiler",
    //     category: "Pets",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/12753820/pexels-photo-12753820.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 133,000",
    //     name: '12" MacBook Air 2021',
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2623968/pexels-photo-2623968.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 93,000",
    //     name: 'Chow Chow',
    //     category: "Pets",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/977003/pexels-photo-977003.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 7,500,000",
    //     name: "Maserati Black Convertible Coupé",
    //     category: "Vehicles",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 2,200,000",
    //     name: "SONY X^6 Videography Setup",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5273012/pexels-photo-5273012.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 800",
    //     name: "Grapes @ KG",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/102061/pexels-photo-102061.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 230,000",
    //     name: "Apple MacBook Air Pro 2022",
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/3353621/pexels-photo-3353621.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 2,000",
    //     name: "Cardigan sweaters @",
    //     category: "Fashion",
    //     location: "Donholm, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 110,000",
    //     name: "SONY Camera Lens",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2318990/pexels-photo-2318990.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 63,000",
    //     name: "Golden Retriever",
    //     category: "Pets",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1413412/pexels-photo-1413412.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 2,700,000",
    //     name: "Kawasaki Angelis Imam 2021",
    //     category: "Vehicles",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1833306/pexels-photo-1833306.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 144,000",
    //     name: "Apple MacBook Air Pro 2022",
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 14,000,000",
    //     name: "Mercedes AMG GT Coupe",
    //     category: "Vehicles",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2095597/pexels-photo-2095597.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 2,300,000",
    //     name: "SONY GEN3 Rolleiflex Editions",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/821738/pexels-photo-821738.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 870,000",
    //     name: "Antique Rolleiflex 1966",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/4005569/pexels-photo-4005569.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 590,000",
    //     name: "Apple MacBook Pro",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1394641/pexels-photo-1394641.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 34,500",
    //     name: "Samsung Galaxy S Series [S7]",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1447264/pexels-photo-1447264.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 980,500",
    //     name: "Sony Exquisite Set",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5793953/pexels-photo-5793953.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 146,500",
    //     name: "Apple MacBook Air 13 8GB RAM, 512GB ROM",
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1738637/pexels-photo-1738637.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 90,500",
    //     name: "Canon EOS 6D Mark II",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/4787588/pexels-photo-4787588.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 198,000",
    //     name: 'Apple MacBook Air 15" 2022',
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1787234/pexels-photo-1787234.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 175,000",
    //     name: 'Canon EOS RP',
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7129180/pexels-photo-7129180.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 4,500",
    //     name: 'Carrots @ 90KG',
    //     category: "Agriculture",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1178337/pexels-photo-1178337.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 249,000",
    //     name: 'Sony Alpha a6400 with 16-50mm',
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/3707744/pexels-photo-3707744.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 184,000",
    //     name: "iPhone 14 Pro Max",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7319172/pexels-photo-7319172.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 800",
    //     name: "Plain T-Shirts",
    //     category: "Fashion",
    //     location: "City Cabanas, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 156,000",
    //     name: "iPhone 14 Pro Max",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5947548/pexels-photo-5947548.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 100",
    //     name: "Ceremonial Balloons @",
    //     category: "Interior",
    //     location: "CBD, Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 2,105,000",
    //     name: "Canon Videography XM Series 4",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/50614/pexels-photo-50614.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 78,000",
    //     name: "Samsung Galaxy S8",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1595243/pexels-photo-1595243.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 198,000",
    //     name: "Nikon D5600 Dslr Camera + Lens",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 22,000",
    //     name: "iPhone 6s",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1787220/pexels-photo-1787220.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 102,700",
    //     name: "Canon EOS 5D Mark IV with 24-105mm Lens",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/5529596/pexels-photo-5529596.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 370",
    //     name: "Eggplants",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2095594/pexels-photo-2095594.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 436,000",
    //     name: "R.E.D Raven Sachtler",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2386429/pexels-photo-2386429.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 459,000",
    //     name: "Sony Alpha A6400 Mirrorless Digital Camera With 16-50mm Lens",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7125435/pexels-photo-7125435.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 198,000",
    //     name: "Coffee Berries @ 90KG",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/248526/pexels-photo-248526.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 12,300",
    //     name: "Samsung Galaxy S4",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2100075/pexels-photo-2100075.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 177,000",
    //     name: "Drone Camera Set",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7129145/pexels-photo-7129145.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 56,000",
    //     name: "Potatoes @ 110KG",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2072060/pexels-photo-2072060.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 677,000",
    //     name: "PC (Setup Inclusive)",
    //     category: "Computers",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/4022090/pexels-photo-4022090.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 400",
    //     name: "Straw Berries @ KG",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1710481/pexels-photo-1710481.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 15,700",
    //     name: "Samsung Galaxy S5",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/2481177/pexels-photo-2481177.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 235,700",
    //     name: "Apple PC",
    //     category: "Computers",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1181269/pexels-photo-1181269.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 100,000",
    //     name: "Apple MacBook Air 1",
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/7125434/pexels-photo-7125434.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 180,000",
    //     name: "Coffee Berries @ Sack(90KG)",
    //     category: "Agriculture",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/3756879/pexels-photo-3756879.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 45,000",
    //     name: "iPhone XR",
    //     category: "Phones",
    //     location: "Kericho",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 120,000",
    //     name: "Apple MacBook Pro 13 2020",
    //     category: "Laptops",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/821749/pexels-photo-821749.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 520,000",
    //     name: "Sigma Manfrotto Ed.4",
    //     category: "Cameras",
    //     location: "Kitale",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/837268/pexels-photo-837268.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 11,000",
    //     name: "iPhone 5",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/1082663/pexels-photo-1082663.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 90,000",
    //     name: "Canon EOS R5",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/3586249/pexels-photo-3586249.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 39,450",
    //     name: "iPhone 7 + Stylus",
    //     category: "Phones",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
    // {
    //     link: "https://images.pexels.com/photos/249597/pexels-photo-249597.jpeg?auto=compress&cs=tinysrgb&w=600",
    //     srcSet: ["link1", "link2", "link2"],
    //     price: "KSh 100,450",
    //     name: "Nikon Z5",
    //     category: "Cameras",
    //     location: "Nairobi",
    //     mobile: "+254717405109",
    //     priceNegotiable: false,
    //     used: false,
    //     seller: "John Sila",
    //     features: ["feature1","feature2","feature3"],
    // },
]

export default moreGoods;