const moreGoods = [
    {
        link: "https://hapakenya.com/wp-content/uploads/2021/02/uber-chapchap.jpg",
        price: "",
        name: "Request a Cab",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6476595/pexels-photo-6476595.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Hire a developer to create your website",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://5.imimg.com/data5/SELLER/Default/2022/4/IB/CK/KH/55920930/goods-transport-service.jpg",
        price: "",
        name: "Move your items",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://pbs.twimg.com/media/DfWoRyZWAAALvR8.jpg",
        price: "",
        name: "Contact a freelancer",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://cdn.corporatefinanceinstitute.com/assets/accounting.jpeg",
        price: "",
        name: "Get a CPA",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://cdn.jdpower.com/Average%20Weight%20Of%20A%20Car.jpg",
        price: "KSh 3,200,000",
        name: "Mercedes Benz C200 2015",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2179865/pexels-photo-2179865.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 120,000",
        name: "Sony Camera Lens 34.70/45",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6294104/pexels-photo-6294104.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 330",
        name: "Eggs @ Tray",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6280436/pexels-photo-6280436.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 7,100",
        name: "Burnt Clay Nursery Buckets",
        category: "Agriculture",
        location: "Kinoo, Kiambu",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://cdn-images.farfetch-contents.com/19/08/44/83/19084483_42150059_600.jpg",
        price: "KSh 2,700",
        name: "Essential Hoodies",
        category: "Fashion",
        location: "Thika, Kiambu",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5625110/pexels-photo-5625110.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 130",
        name: "Packaging bags @",
        category: "Fashion",
        location: "Industrial Area, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2252541/pexels-photo-2252541.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 40,000",
        name: "Pigs @ & 4-Month Old",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://cdn.24.co.za/files/Cms/General/d/6150/d2bd910b7e504f3ab3e9c7fbc82c96bb.jpg",
        price: "",
        name: "Kinyozi (Contact a barber)",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/52518/jeans-pants-blue-shop-52518.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 870",
        name: "Blue Jeans @",
        category: "Fashion",
        location: "Mfangano Street, Nairobi CBD",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7319324/pexels-photo-7319324.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 140",
        name: "Package bags",
        category: "Fashion",
        location: "Dandora, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2920064/pexels-photo-2920064.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 4,650,000",
        name: "Hyundai Qashqai 2022 Model",
        category: "Vehicles",
        location: "Starehe, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2403391/pexels-photo-2403391.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Get to your nearest restaurant",
        category: "Services",
        location: "Upperhill, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2912108/pexels-photo-2912108.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Wines (Delivery)",
        category: "Drinks",
        location: "Westlands, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/952264/pexels-photo-952264.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 72,000",
        name: "Nikon D7500",
        category: "Cameras",
        location: "CBD, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5709648/pexels-photo-5709648.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 3,200",
        name: "Hawaiian Hat for Women",
        category: "Fashion",
        location: "CBD, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6126310/pexels-photo-6126310.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Outdoor Dining Palace",
        category: "Food",
        location: "Westlands, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2995012/pexels-photo-2995012.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 72,000",
        name: "Dining Table",
        category: "Interior",
        location: "Makadara, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5230908/pexels-photo-5230908.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 12,000",
        name: "Agricultural carts",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2002717/pexels-photo-2002717.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 17,500",
        name: "Women's handbags",
        category: "Fashion",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5709655/pexels-photo-5709655.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 24,400",
        name: "Assorted Fabric Bags",
        category: "Fashion",
        location: "Eastleigh, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2129654/pexels-photo-2129654.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 1,000",
        name: "Adult Chicken",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6294166/pexels-photo-6294166.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 350",
        name: "Eggs @ Tray",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5945657/pexels-photo-5945657.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 1,350",
        name: "Tomatoes @ 90 KG",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5699068/pexels-photo-5699068.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 8,550",
        name: "Cowboy Hats",
        category: "Fashion",
        location: "CBD, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7832983/pexels-photo-7832983.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Order Fast Food + Delivery",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/11568799/pexels-photo-11568799.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Contact your nearest fast food restaurant",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/6280388/pexels-photo-6280388.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 450",
        name: "Spinach @ 15KG",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://media.istockphoto.com/id/1158134822/photo/kfc-style-fried-chicken-nuggets-takeaway-in-black-container.jpg?b=1&s=612x612&w=0&k=20&c=86DcrfP_oV4GO5BXeYanj5dj0t64EqOld1fMC_6f34U=",
        price: "",
        name: "Order Fast Food + Delivery",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1841120/pexels-photo-1841120.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 7,000,000",
        name: "Cadillac 1979 Etzy Model",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/794435/pexels-photo-794435.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 4,300,000",
        name: "BMW M3 2015 M Competition Edition",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5905486/pexels-photo-5905486.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "",
        name: "Hire a Tutor",
        category: "Services",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2023384/pexels-photo-2023384.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 48,000",
        name: "Rottweiler",
        category: "Pets",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/12753820/pexels-photo-12753820.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 133,000",
        name: '12" MacBook Air 2021',
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2623968/pexels-photo-2623968.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 93,000",
        name: 'Chow Chow',
        category: "Pets",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/977003/pexels-photo-977003.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 7,500,000",
        name: "Maserati Black Convertible Coupé",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/66134/pexels-photo-66134.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 2,200,000",
        name: "SONY X^6 Videography Setup",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5273012/pexels-photo-5273012.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 800",
        name: "Grapes @ KG",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/102061/pexels-photo-102061.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 230,000",
        name: "Apple MacBook Air Pro 2022",
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/3353621/pexels-photo-3353621.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 2,000",
        name: "Cardigan sweaters @",
        category: "Fashion",
        location: "Donholm, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 110,000",
        name: "SONY Camera Lens",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2318990/pexels-photo-2318990.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 63,000",
        name: "Golden Retriever",
        category: "Pets",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1413412/pexels-photo-1413412.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 2,700,000",
        name: "Kawasaki Angelis Imam 2021",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1833306/pexels-photo-1833306.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 144,000",
        name: "Apple MacBook Air Pro 2022",
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/241316/pexels-photo-241316.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 14,000,000",
        name: "Mercedes AMG GT Coupe",
        category: "Vehicles",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2095597/pexels-photo-2095597.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 2,300,000",
        name: "SONY GEN3 Rolleiflex Editions",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/821738/pexels-photo-821738.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 870,000",
        name: "Antique Rolleiflex 1966",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/4005569/pexels-photo-4005569.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 590,000",
        name: "Apple MacBook Pro",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1394641/pexels-photo-1394641.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 34,500",
        name: "Samsung Galaxy S Series [S7]",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1447264/pexels-photo-1447264.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 980,500",
        name: "Sony Exquisite Set",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5793953/pexels-photo-5793953.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 146,500",
        name: "Apple MacBook Air 13 8GB RAM, 512GB ROM",
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1738637/pexels-photo-1738637.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 90,500",
        name: "Canon EOS 6D Mark II",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/4787588/pexels-photo-4787588.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 198,000",
        name: 'Apple MacBook Air 15" 2022',
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1787234/pexels-photo-1787234.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 175,000",
        name: 'Canon EOS RP',
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7129180/pexels-photo-7129180.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 4,500",
        name: 'Carrots @ 90KG',
        category: "Agriculture",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1178337/pexels-photo-1178337.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 249,000",
        name: 'Sony Alpha a6400 with 16-50mm',
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/3707744/pexels-photo-3707744.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 184,000",
        name: "iPhone 14 Pro Max",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7319172/pexels-photo-7319172.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 800",
        name: "Plain T-Shirts",
        category: "Fashion",
        location: "City Cabanas, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/4195325/pexels-photo-4195325.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 156,000",
        name: "iPhone 14 Pro Max",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5947548/pexels-photo-5947548.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 100",
        name: "Ceremonial Balloons @",
        category: "Interior",
        location: "CBD, Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2873486/pexels-photo-2873486.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 2,105,000",
        name: "Canon Videography XM Series 4",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/50614/pexels-photo-50614.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 78,000",
        name: "Samsung Galaxy S8",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1595243/pexels-photo-1595243.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 198,000",
        name: "Nikon D5600 Dslr Camera + Lens",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 22,000",
        name: "iPhone 6s",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1787220/pexels-photo-1787220.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 102,700",
        name: "Canon EOS 5D Mark IV with 24-105mm Lens",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/5529596/pexels-photo-5529596.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 370",
        name: "Eggplants",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2095594/pexels-photo-2095594.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 436,000",
        name: "R.E.D Raven Sachtler",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2386429/pexels-photo-2386429.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 459,000",
        name: "Sony Alpha A6400 Mirrorless Digital Camera With 16-50mm Lens",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7125435/pexels-photo-7125435.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 198,000",
        name: "Coffee Berries @ 90KG",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/248526/pexels-photo-248526.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 12,300",
        name: "Samsung Galaxy S4",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2100075/pexels-photo-2100075.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 177,000",
        name: "Drone Camera Set",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7129145/pexels-photo-7129145.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 56,000",
        name: "Potatoes @ 110KG",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2072060/pexels-photo-2072060.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 677,000",
        name: "PC (Setup Inclusive)",
        category: "Computers",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/4022090/pexels-photo-4022090.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 400",
        name: "Straw Berries @ KG",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1710481/pexels-photo-1710481.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 15,700",
        name: "Samsung Galaxy S5",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/2481177/pexels-photo-2481177.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 235,700",
        name: "Apple PC",
        category: "Computers",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1181269/pexels-photo-1181269.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 100,000",
        name: "Apple MacBook Air 1",
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/7125434/pexels-photo-7125434.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 180,000",
        name: "Coffee Berries @ Sack(90KG)",
        category: "Agriculture",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/3756879/pexels-photo-3756879.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 45,000",
        name: "iPhone XR",
        category: "Phones",
        location: "Kericho",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 120,000",
        name: "Apple MacBook Pro 13 2020",
        category: "Laptops",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/821749/pexels-photo-821749.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 520,000",
        name: "Sigma Manfrotto Ed.4",
        category: "Cameras",
        location: "Kitale",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/837268/pexels-photo-837268.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 11,000",
        name: "iPhone 5",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/1082663/pexels-photo-1082663.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 90,000",
        name: "Canon EOS R5",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/3586249/pexels-photo-3586249.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 39,450",
        name: "iPhone 7 + Stylus",
        category: "Phones",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
    {
        link: "https://images.pexels.com/photos/249597/pexels-photo-249597.jpeg?auto=compress&cs=tinysrgb&w=600",
        price: "KSh 100,450",
        name: "Nikon Z5",
        category: "Cameras",
        location: "Nairobi",
        mobile: "+254717 405109",
        priceNegotiable: false,
        used: false,
        seller: "John Sila",
        additionalSpecs: [],
    },
]

export default moreGoods;